report: report.tex
	xelatex $<

session1: session1.tex
	xelatex $<

session2: session2.tex
	xelatex $<

source: source.tex
	xelatex $<

wireshark: wireshark.tex
	xelatex $<

router: router.tex
	xelatex $<

.PHONY: clean

clean: 
	rm *.log *.aux *.xdv *.fls *.fdb_latexmk *.out *.toc *.gz *.bbl *.blg
